# config/meta.yml
meta_product_name: "ManKai"
meta_title: "ManKai - Partage ta passion pour les mangas avec les personnes autour de toi"
meta_description: "Une application mobile qui permet d'échanger des mangas avec d'autres utilisateurs et de découvrir de nouvelles pépites."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@VIZMedia" # required for Twitter Cards
